package com.example.dudu.awsexample.Models;

/**
 * Created by Dudu on 7/30/17.
 */

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

import java.util.List;
import java.util.Map;
import java.util.Set;

    @DynamoDBTable(tableName = "category")

    public class Category {
        private String _id;
        private String _name;

        @DynamoDBHashKey(attributeName = "id")
        @DynamoDBAutoGeneratedKey
        @DynamoDBAttribute(attributeName = "id")
        public String getId() {
            return _id;
        }

        public void setId(final String _id) {
            this._id = _id;
        }
        @DynamoDBAttribute(attributeName = "name")
        public String getName() {
            return _name;
        }

        public void setName(final String _name) {
            this._name = _name;
        }

    }


