package com.example.dudu.awsexample.Models;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

import java.util.List;
import java.util.Map;
import java.util.Set;

@DynamoDBTable(tableName = "department")

public class Department {
    private String _id;
    private String _categoryId;
    private String _description;
    private Double _endTime;
    private List<String> _holidays;
    private Double _lat;
    private Double _lng;
    private String _name;
    private Double _startTime;
    private String _street;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "id")
    public String getId() {
        return _id;
    }

    public void setId(final String _id) {
        this._id = _id;
    }
    @DynamoDBAttribute(attributeName = "cat_id")
    public String getCategoryId() {
        return _categoryId;
    }

    public void setCategoryId(final String _categoryId) {
        this._categoryId = _categoryId;
    }
    @DynamoDBAttribute(attributeName = "description")
    public String getDescription() {
        return _description;
    }

    public void setDescription(final String _description) {
        this._description = _description;
    }
    @DynamoDBAttribute(attributeName = "endTime")
    public Double getEndTime() {
        return _endTime;
    }

    public void setEndTime(final Double _endTime) {
        this._endTime = _endTime;
    }
    @DynamoDBAttribute(attributeName = "holidays")
    public List<String> getHolidays() {
        return _holidays;
    }

    public void setHolidays(final List<String> _holidays) {
        this._holidays = _holidays;
    }
    @DynamoDBAttribute(attributeName = "latitude")
    public Double getLat() {
        return _lat;
    }

    public void setLat(final Double _lat) {
        this._lat = _lat;
    }
    @DynamoDBAttribute(attributeName = "longtude")
    public Double getLng() {
        return _lng;
    }

    public void setLng(final Double _lng) {
        this._lng = _lng;
    }
    @DynamoDBAttribute(attributeName = "name")
    public String getName() {
        return _name;
    }

    public void setName(final String _name) {
        this._name = _name;
    }

    @DynamoDBAttribute(attributeName = "startTime")
    public Double getStartTime() {
        return _startTime;
    }

    public void setStartTime(final Double _startTime) {
        this._startTime = _startTime;
    }
    @DynamoDBAttribute(attributeName = "street")
    public String getStreet() {
        return _street;
    }

    public void setStreet(final String _street) {
        this._street = _street;
    }

}
