package com.example.dudu.awsexample.Models;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

import java.util.List;
import java.util.Map;
import java.util.Set;

@DynamoDBTable(tableName = "rating")

public class Rating {
    private String _id;
    private String _departmentid;
    private String _ratingCount;
    private String _ratingName;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "id")

    public String  getId() {
        return _id;
    }

    public void setId(final String _id) {
        this._id = _id;
    }
    @DynamoDBAttribute(attributeName = "dep_id")
    public String getDepartmentid() {
        return _departmentid;
    }

    public void setDepartmentid(final String _departmentid) {
        this._departmentid = _departmentid;
    }
    @DynamoDBAttribute(attributeName = "ratingCount")
    public String getRatingCount() {
        return _ratingCount;
    }

    public void setRatingCount(final String _ratingCount) {
        this._ratingCount = _ratingCount;
    }
    @DynamoDBAttribute(attributeName = "ratingName")
    public String getRatingName() {
        return _ratingName;
    }

    public void setRatingName(final String _ratingName) {
        this._ratingName = _ratingName;
    }

}
